# Generated by Django 2.1.7 on 2019-04-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eFarmer', '0002_auto_20190407_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phoneNo',
            field=models.IntegerField(),
        ),
    ]
