# Generated by Django 2.1.7 on 2019-04-08 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eFarmer', '0003_auto_20190407_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonSaleIndex',
            fields=[
                ('emailid', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('noOfItemsAtSale', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='saleProductTable',
            fields=[
                ('productId', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('typeOfSale', models.CharField(choices=[('L', 'LEASE'), ('S', 'SALE'), ('R', 'RENT')], max_length=1)),
                ('nameOfProduct', models.CharField(max_length=256)),
                ('descriptionOfProduct', models.CharField(max_length=1000)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eFarmer.Users')),
            ],
        ),
    ]
