# Generated by Django 2.1.7 on 2019-04-08 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eFarmer', '0004_personsaleindex_saleproducttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandiId', models.CharField(max_length=50, unique=True)),
                ('mandiName', models.CharField(max_length=100)),
                ('mandiAddress', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MandiRateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfItem', models.CharField(max_length=50)),
                ('maxRequirement', models.IntegerField(default=10)),
                ('mandiId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eFarmer.Mandi')),
                ('vendorId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eFarmer.Users')),
            ],
        ),
    ]
